package io.warp10.warpscriptDSL
 
// 
// WarpScript KOTLINDSL
// @author aurrelhebert 
// @license apache 2.0 
// 
 
// Autogenerated code
 
fun WarpScript.eulerConstant(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("e"), init) 
} 

fun WarpScript.maxLong(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("MAXLONG"), init) 
} 

fun WarpScript.minLong(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("MINLONG"), init) 
} 

fun WarpScript.notANumber(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("NaN"), init) 
} 

fun WarpScript.nullWarp10(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("NULL"), init) 
} 

fun WarpScript.pi(init: Element.() -> Unit = {}) : Functions {
    return initTag(Functions("PI"), init) 
} 
