package io.warp10.warpscriptDSL
 
// 
// WarpScript KOTLINDSL
// @author aurrelhebert 
// @license apache 2.0 
// 
 
// Autogenerated code
 
fun WarpScript.drop() : Functions {
    return initTag(Functions("DROP"), {}) 
} 

fun WarpScript.swap() : Functions {
    return initTag(Functions("SWAP"), {}) 
} 

fun WarpScript.clear() : Functions {
    return initTag(Functions("CLEAR"), {}) 
} 

fun WarpScript.run() : Functions {
    return initTag(Functions("RUN"), {}) 
} 

fun WarpScript.sort() : Functions {
    return initTag(Functions("SORT"), {}) 
} 

fun WarpScript.evalSecure() : Functions {
    return initTag(Functions("EVALSecure"), {}) 
} 

fun WarpScript.loadWarp() : Functions {
    return initTag(Functions("LOAD"), {}) 
} 

fun WarpScript.snapshotAll() : Functions {
    return initTag(Functions("SNAPSHOTALL"), {}) 
} 

fun WarpScript.nullWarp() : Functions {
    return initTag(Functions("NULL"), {}) 
} 

fun WarpScript.eval() : Functions {
    return initTag(Functions("EVAL"), {}) 
} 

fun WarpScript.stop() : Functions {
    return initTag(Functions("STOP"), {}) 
} 

fun WarpScript.now() : Functions {
    return initTag(Functions("NOW"), {}) 
} 

fun WarpScript.snapshot() : Functions {
    return initTag(Functions("SNAPSHOT"), {}) 
} 

